### PR TITLE
Fixed failing tests

### PR DESCRIPTION
**Pull request by coderforaliving**
@Janekdererste  Please review the changes

### CODE REVIEW

**Comment by kt86** [comment]
We can not make the large database files publicly available .... please use either small samples files, as they are already online or access the values using the encrypted files. Thanks a lot!

For not having them here in the repo via the history, please use a new branch where you only commit the code-changes (and maybe the sample-files)

**Comment by kt86** [comment]
added @Janekdererste as Reviewer, because he was asked in PR comment to review the changes

**Review by Janekdererste — CHANGES_REQUESTED** [review]
Thanks for fixing this. 

The HBEFA-Files are not public. Please 

- close this PR 
- delete the Branch from the GH-repository. 
- make a new branch from 15.x locally
- add the changes into the code you made here
- delete your aravindsasi:14.x branch locally as well
- Now, the interesting part starts. 
    - Either we can add secret variables to the github-actions build, then we can use the encyptet HBEFA-Files from the public-svn
    - Otherwise, we need Pseudo-HBEFA-Files in the repository. The emission contrib in the main repository has such files I think

My preference would be to use pseudo-files, since this is an example others are supposed to run.

**Comment by coderforaliving** [comment]
Closing PR

**Pull request closed without merging**
