### PR TITLE
set matsim-all POM as parent POM

### PR DESCRIPTION
**Pull request by michalmac**
To be fully compatible with the matsim-lib code (dependency versions, selected dependencies, plugins (and their versions), repos etc.). By doing so, code examples will behave almost as if it was one of the modules inside matsim-libs.

I will wait with merging it to hear what you think about this setup.

### CODE REVIEW

**Comment by rakow** [comment]
I have used it like this in other projects now and haven't noticed any drawbacks.  It could lead to confusion for some users because plugins are configured behind the scene, which is not apparent for beginners. Especially, the enforce plugin can lead to errors quite easily, and I would image beginners would be totally lost on what to do.

**Comment by michalmac** [comment]
> Especially, the enforce plugin can lead to errors quite easily, and I would image beginners would be totally lost on what to do.

On one hand, I agree. I also do not like is that it inherits some profiles (however, we can move most/all of them from matsim-all to matsim - so this issue is easy to resolve). On the other hand, not using the right dependency version may be even trickier to notice, even for expert users.

Maybe it also depends on the context: maybe we want to use this "parent POM" approach for `matsim-code examples` (so we have 100% compatibility for code samples and make it easy to maintain) but not for `matsim-example-project` (that is targeted towards beginners)?

**Comment by kainagel** [comment]
I have no intuition for the consequences.  I would agree that we need to keep matsim-example-project easy to understand, but matsim-code-examples easy to maintain.  Meaning that it is probably ok to make this change with matsim-code-examples.  But not with matsim-example-project.

**Comment by michalmac** [comment]
Thanks for the feedback. I will give it a try and merge it. We can also easily undo this change whenever we feel we do not want to have this setup.

**Pull request merged**
